version: '3.8'

services:
  todolist-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - todolist-network

  # Optional: Add a reverse proxy for SSL termination
  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - todolist-app
    restart: unless-stopped
    networks:
      - todolist-network
    profiles:
      - production

networks:
  todolist-network:
    driver: bridge

volumes:
  ssl-certs:
    driver: local